# Configuration metadata
configuration-name: Standard Configuration 

# For the case of stitching two cameras:
left-index: 1
right-index: 2

# For the case of stitching two videos:
left-video-path: /Users/lukefernandez/Projects/stitch-flex/app/storage/synced_videos/cam3/2.mp4
right-video-path: /Users/lukefernandez/Projects/stitch-flex/app/storage/synced_videos/cam4/2.mp4

# For the case of stitching between two and four cameras:
first-index: 1
second-index: 2
third-index: 3
fourth-index: 4

# For the case of stitching between two and four videos:
first-video-path: /Users/lukefernandez/Projects/360ls-stitcher/data/videos/2.mp4
second-video-path: /Users/lukefernandez/Projects/360ls-stitcher/data/videos/2.mp4
third-video-path: /Users/lukefernandez/Projects/360ls-stitcher/data/videos/2.mp4
fourth-video-path: /Users/lukefernandez/Projects/360ls-stitcher/data/videos/2.mp4

# Default values for width, height, etc.
width: 640
height: 480 
