# Configuration metadata
name: Standard Configuration 

# For the case of stitching one camera:
camera-index: 0

# For the case of stitching two cameras:
should-stitch: True
left-index: 1
right-index: 2
just-preview: False
should-stream: True
output-path: out.avi
rtmp_url: rtmp://54.227.214.22:1935/live/myStream

# Default values for width, height, etc.
width: 640
height: 480 