language: python
python:
  - "2.7.3"
  
# command to install dependencies
install: "make install"

# command to run tests
script: 
  - make lint

notifications:
  slack: 360ls:7L865GMYEQ3zVwgCSqckWKHI
